name: Build, Minify, and Commit Slider

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with full history.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Node.js (choose your version).
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies.
      - name: Install dependencies
        run: npm install

      # Run the build script to generate dist/slider.min.js.
      - name: Build the slider
        run: npm run build

      # Configure Git.
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Commit and push changes if the built file changed.
      - name: Commit built file if changed
        run: |
          if [ -n "$(git status --porcelain dist/slider.min.js)" ]; then
            git remote set-url origin https://x-access-token:${{ secrets.SLIDER_RELEASE_KEY }}@github.com/FoxyLetterOpener/foxy-js-slider.git
            git add dist/slider.min.js
            git commit -m "chore: update slider.min.js [skip ci]"
            git push
          else
            echo "No changes in dist/slider.min.js, nothing to commit."
          fi
