name: Build and Minify Slider

on:
  push:
    branches:
      - main  # or whichever branch you use for development
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup Node.js (choose your preferred version)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build script
      - name: Build the slider code
        run: npm run build

      # (Optional) You can add steps to run tests or publish your package if needed.
